[Icon Theme]
Name=NT Legacy Icons
Comment=Symbole im Stil von Windows NT 4.0, vollstaendig erzeugt
Inherits=breeze,hicolor
Directories=actions/16,actions/22,actions/32,actions/48,apps/16,apps/22,apps/32,apps/48,devices/16,devices/22,devices/32,devices/48,mimetypes/16,mimetypes/22,mimetypes/32,mimetypes/48,places/16,places/22,places/32,places/48,status/16,status/22,status/32,status/48

[actions/16]
Size=16
Context=Actions
Type=Fixed

[actions/22]
Size=22
Context=Actions
Type=Fixed

[actions/32]
Size=32
Context=Actions
Type=Fixed

[actions/48]
Size=48
Context=Actions
Type=Fixed

[apps/16]
Size=16
Context=Applications
Type=Fixed

[apps/22]
Size=22
Context=Applications
Type=Fixed

[apps/32]
Size=32
Context=Applications
Type=Fixed

[apps/48]
Size=48
Context=Applications
Type=Fixed

[devices/16]
Size=16
Context=Devices
Type=Fixed

[devices/22]
Size=22
Context=Devices
Type=Fixed

[devices/32]
Size=32
Context=Devices
Type=Fixed

[devices/48]
Size=48
Context=Devices
Type=Fixed

[mimetypes/16]
Size=16
Context=MimeTypes
Type=Fixed

[mimetypes/22]
Size=22
Context=MimeTypes
Type=Fixed

[mimetypes/32]
Size=32
Context=MimeTypes
Type=Fixed

[mimetypes/48]
Size=48
Context=MimeTypes
Type=Fixed

[places/16]
Size=16
Context=Places
Type=Fixed

[places/22]
Size=22
Context=Places
Type=Fixed

[places/32]
Size=32
Context=Places
Type=Fixed

[places/48]
Size=48
Context=Places
Type=Fixed

[status/16]
Size=16
Context=Status
Type=Fixed

[status/22]
Size=22
Context=Status
Type=Fixed

[status/32]
Size=32
Context=Status
Type=Fixed

[status/48]
Size=48
Context=Status
Type=Fixed
