#!/usr/bin/env python3
"""Writes frontpanel/contents/ui/ConfigPage.qml from its config/main.xml: the base of
every settings page, declaring each setting's default (Plasma hands every
page all of them). Run after adding a setting; tests/verify.py checks that
the file is current."""
from pathlib import Path
import xml.etree.ElementTree as ET

HERE = Path(__file__).parent / "frontpanel"


def render():
    names = [e.get("name") for e in ET.parse(HERE / "contents/config/main.xml").iter() if e.tag.endswith("entry")]
    lines = "".join(f"    property var cfg_{name}Default\n" for name in names)
    return ("// Generated by configpage.py from config/main.xml - do not edit.\n"
            "import org.kde.kcmutils as KCM\n\n"
            "// The base of the settings pages. Plasma hands every page every setting's\n"
            "// default; declared here so it takes them quietly. (Not the settings\n"
            "// themselves: Plasma saves every cfg_ property a page has, and an unshown\n"
            "// one would write back a stale value over what the console changed\n"
            "// meanwhile. Each page declares the settings it shows.)\n"
            "KCM.SimpleKCM {\n" + lines + "}\n")


if __name__ == "__main__":
    (HERE / "contents/ui/ConfigPage.qml").write_text(render())
