[Icon Theme]
Name=NTLegacyOS
Comment=Symbole aus den ReactOS-Ressourcen (GPL-2.0)
Inherits=breeze,hicolor
Directories=actions/16,actions/32,actions/48,apps/16,apps/32,apps/48,devices/16,devices/32,devices/48,mimetypes/16,mimetypes/32,mimetypes/48,places/16,places/32,places/48,status/16,status/32,status/48

[actions/16]
Size=16
Context=Actions
Type=Fixed

[actions/32]
Size=32
Context=Actions
Type=Fixed

[actions/48]
Size=48
Context=Actions
Type=Fixed

[apps/16]
Size=16
Context=Apps
Type=Fixed

[apps/32]
Size=32
Context=Apps
Type=Fixed

[apps/48]
Size=48
Context=Apps
Type=Fixed

[devices/16]
Size=16
Context=Devices
Type=Fixed

[devices/32]
Size=32
Context=Devices
Type=Fixed

[devices/48]
Size=48
Context=Devices
Type=Fixed

[mimetypes/16]
Size=16
Context=Mimetypes
Type=Fixed

[mimetypes/32]
Size=32
Context=Mimetypes
Type=Fixed

[mimetypes/48]
Size=48
Context=Mimetypes
Type=Fixed

[places/16]
Size=16
Context=Places
Type=Fixed

[places/32]
Size=32
Context=Places
Type=Fixed

[places/48]
Size=48
Context=Places
Type=Fixed

[status/16]
Size=16
Context=Status
Type=Fixed

[status/32]
Size=32
Context=Status
Type=Fixed

[status/48]
Size=48
Context=Status
Type=Fixed
